config/routes.rb
Rails.application.routes.draw do
  resources :neighborhoods
  resources :municipalities
  resources :mayors
  root :to => "municipalities#index" # mostrar las municipalidades por defecto
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mayor.rb
class Mayor < ApplicationRecord
    has_one :municipality

    # Validaciones
    validates :phone, :numericality => { :only_integer => true }
    validates :name, :last_name, :nacionality, :mail, :phone, :presence => true
    validates_format_of :mail, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

    def full_name
        self.name + " " + self.last_name
    end
end

app/models/municipality.rb
class Municipality < ApplicationRecord
  belongs_to :mayor
  validates_uniqueness_of :mayor_id

  validates :name, :foundation_year, :URL, :mail, :mayor_id, :presence => true
  validates_format_of :mail, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  has_many :neighborhood
end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  belongs_to :municipality

  # Validaciones
  validates :population, :block_count, :numericality => { :only_integer => true }
  validates :name, :block_count, :population, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mayors_controller.rb
class MayorsController < ApplicationController
  before_action :set_mayor, only: [:show, :edit, :update, :destroy]

  # GET /mayors
  # GET /mayors.json
  def index
    @mayors = Mayor.all
  end

  # GET /mayors/1
  # GET /mayors/1.json
  def show
  end

  # GET /mayors/new
  def new
    @mayor = Mayor.new
  end

  # GET /mayors/1/edit
  def edit
  end

  # POST /mayors
  # POST /mayors.json
  def create
    @mayor = Mayor.new(mayor_params)

    respond_to do |format|
      if @mayor.save
        format.html { redirect_to @mayor, notice: 'Mayor was successfully created.' }
        format.json { render :show, status: :created, location: @mayor }
      else
        format.html { render :new }
        format.json { render json: @mayor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mayors/1
  # PATCH/PUT /mayors/1.json
  def update
    respond_to do |format|
      if @mayor.update(mayor_params)
        format.html { redirect_to @mayor, notice: 'Mayor was successfully updated.' }
        format.json { render :show, status: :ok, location: @mayor }
      else
        format.html { render :edit }
        format.json { render json: @mayor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mayors/1
  # DELETE /mayors/1.json
  def destroy
    @mayor.destroy
    respond_to do |format|
      format.html { redirect_to mayors_url, notice: 'Mayor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mayor
      @mayor = Mayor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mayor_params
      params.require(:mayor).permit(:name, :last_name, :nacionality, :mail, :phone)
    end
end

app/controllers/municipalities_controller.rb
class MunicipalitiesController < ApplicationController
  before_action :set_municipality, only: [:show, :edit, :update, :destroy]

  # GET /municipalities
  # GET /municipalities.json
  def index
    @municipalities = Municipality.all
  end

  # GET /municipalities/1
  # GET /municipalities/1.json
  def show
  end

  # GET /municipalities/new
  def new
    @municipality = Municipality.new
  end

  # GET /municipalities/1/edit
  def edit
  end

  # POST /municipalities
  # POST /municipalities.json
  def create
    @municipality = Municipality.new(municipality_params)

    respond_to do |format|
      if @municipality.save
        format.html { redirect_to @municipality, notice: 'Municipality was successfully created.' }
        format.json { render :show, status: :created, location: @municipality }
      else
        format.html { render :new }
        format.json { render json: @municipality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipalities/1
  # PATCH/PUT /municipalities/1.json
  def update
    respond_to do |format|
      if @municipality.update(municipality_params)
        format.html { redirect_to @municipality, notice: 'Municipality was successfully updated.' }
        format.json { render :show, status: :ok, location: @municipality }
      else
        format.html { render :edit }
        format.json { render json: @municipality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipalities/1
  # DELETE /municipalities/1.json
  def destroy
    @municipality.destroy
    respond_to do |format|
      format.html { redirect_to municipalities_url, notice: 'Municipality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipality
      @municipality = Municipality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def municipality_params
      params.require(:municipality).permit(:name, :foundation_year, :URL, :mail, :mayor_id)
    end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: [:show, :edit, :update, :destroy]

  # GET /neighborhoods
  # GET /neighborhoods.json
  def index
    @neighborhoods = Neighborhood.all
  end

  # GET /neighborhoods/1
  # GET /neighborhoods/1.json
  def show
  end

  # GET /neighborhoods/new
  def new
    @neighborhood = Neighborhood.new
  end

  # GET /neighborhoods/1/edit
  def edit
  end

  # POST /neighborhoods
  # POST /neighborhoods.json
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)

    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully created.' }
        format.json { render :show, status: :created, location: @neighborhood }
      else
        format.html { render :new }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighborhoods/1
  # PATCH/PUT /neighborhoods/1.json
  def update
    respond_to do |format|
      if @neighborhood.update(neighborhood_params)
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully updated.' }
        format.json { render :show, status: :ok, location: @neighborhood }
      else
        format.html { render :edit }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighborhoods/1
  # DELETE /neighborhoods/1.json
  def destroy
    @neighborhood.destroy
    respond_to do |format|
      format.html { redirect_to neighborhoods_url, notice: 'Neighborhood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighborhood
      @neighborhood = Neighborhood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighborhood_params
      params.require(:neighborhood).permit(:name, :block_count, :population, :municipality_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mayors_helper.rb
module MayorsHelper
end

app/helpers/municipalities_helper.rb
module MunicipalitiesHelper
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MunicipalityManage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Mayor', mayors_path %>
    <%= link_to 'Neighborhood', neighborhoods_path %>
    <%= link_to 'Municipality', municipalities_path %>
    <%= yield %>
  </body>
</html>

app/views/mayors/_form.html.erb
<%= form_with(model: mayor, local: true) do |form| %>
  <% if mayor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mayor.errors.count, "error") %> prohibited this mayor from being saved:</h2>

      <ul>
      <% mayor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :nacionality %>
    <%= form.text_field :nacionality %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mayors/edit.html.erb
<h1>Editing Mayor</h1>

<%= render 'form', mayor: @mayor %>

<%= link_to 'Show', @mayor %> |
<%= link_to 'Back', mayors_path %>

app/views/mayors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mayors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Nacionality</th>
      <th>Mail</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mayors.each do |mayor| %>
      <tr>
        <td><%= mayor.name %></td>
        <td><%= mayor.last_name %></td>
        <td><%= mayor.nacionality %></td>
        <td><%= mayor.mail %></td>
        <td><%= mayor.phone %></td>
        <td><%= link_to 'Show', mayor %></td>
        <td><%= link_to 'Edit', edit_mayor_path(mayor) %></td>
        <td><%= link_to 'Destroy', mayor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mayor', new_mayor_path %>

app/views/mayors/new.html.erb
<h1>New Mayor</h1>

<%= render 'form', mayor: @mayor %>

<%= link_to 'Back', mayors_path %>

app/views/mayors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mayor.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @mayor.last_name %>
</p>

<p>
  <strong>Nacionality:</strong>
  <%= @mayor.nacionality %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @mayor.mail %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @mayor.phone %>
</p>

<%= link_to 'Edit', edit_mayor_path(@mayor) %> |
<%= link_to 'Back', mayors_path %>

app/views/municipalities/_form.html.erb
<%= form_with(model: municipality, local: true) do |form| %>
  <% if municipality.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(municipality.errors.count, "error") %> prohibited this municipality from being saved:</h2>

      <ul>
      <% municipality.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :foundation_year %>
    <%= form.datetime_select :foundation_year, start_year:1900 %>
  </div>

  <div class="field">
    <%= form.label :URL %>
    <%= form.text_field :URL %>
  </div>

  <div class="field">
    <%= form.label :mail %>
    <%= form.text_field :mail %>
  </div>

  <div class="field">
    <%= form.label :mayor_id %>
    <%= collection_select(:municipality, :mayor_id, Mayor.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/municipalities/edit.html.erb
<h1>Editing Municipality</h1>

<%= render 'form', municipality: @municipality %>

<%= link_to 'Show', @municipality %> |
<%= link_to 'Back', municipalities_path %>

app/views/municipalities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Municipalities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Foundation year</th>
      <th>Url</th>
      <th>Mail</th>
      <th>Mayor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @municipalities.each do |municipality| %>
      <tr>
        <td><%= municipality.name %></td>
        <td><%= municipality.foundation_year %></td>
        <td><%= municipality.URL %></td>
        <td><%= municipality.mail %></td>
        <td><%= municipality.mayor.full_name %></td>
        <td><%= link_to 'Show', municipality %></td>
        <td><%= link_to 'Edit', edit_municipality_path(municipality) %></td>
        <td><%= link_to 'Destroy', municipality, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Municipality', new_municipality_path %>

app/views/municipalities/new.html.erb
<h1>New Municipality</h1>

<%= render 'form', municipality: @municipality %>

<%= link_to 'Back', municipalities_path %>

app/views/municipalities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @municipality.name %>
</p>

<p>
  <strong>Foundation year:</strong>
  <%= @municipality.foundation_year %>
</p>

<p>
  <strong>Url:</strong>
  <%= @municipality.URL %>
</p>

<p>
  <strong>Mail:</strong>
  <%= @municipality.mail %>
</p>

<p>
  <strong>Mayor:</strong>
  <%= @municipality.mayor.full_name %>
</p>

<%= link_to 'Edit', edit_municipality_path(@municipality) %> |
<%= link_to 'Back', municipalities_path %>

app/views/neighborhoods/_form.html.erb
<%= form_with(model: neighborhood, local: true) do |form| %>
  <% if neighborhood.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(neighborhood.errors.count, "error") %> prohibited this neighborhood from being saved:</h2>

      <ul>
      <% neighborhood.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :block_count %>
    <%= form.number_field :block_count %>
  </div>

  <div class="field">
    <%= form.label :population %>
    <%= form.number_field :population %>
  </div>

  <div class="field">
    <%= form.label :municipality_id %>
    <%= collection_select(:neighborhood, :municipality_id, Municipality.all, :id, :name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/neighborhoods/edit.html.erb
<h1>Editing Neighborhood</h1>

<%= render 'form', neighborhood: @neighborhood %>

<%= link_to 'Show', @neighborhood %> |
<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Neighborhoods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Block count</th>
      <th>Population</th>
      <th>Municipality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @neighborhoods.each do |neighborhood| %>
      <tr>
        <td><%= neighborhood.name %></td>
        <td><%= neighborhood.block_count %></td>
        <td><%= neighborhood.population %></td>
        <td><%= neighborhood.municipality.name %></td>
        <td><%= link_to 'Show', neighborhood %></td>
        <td><%= link_to 'Edit', edit_neighborhood_path(neighborhood) %></td>
        <td><%= link_to 'Destroy', neighborhood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Neighborhood', new_neighborhood_path %>

app/views/neighborhoods/new.html.erb
<h1>New Neighborhood</h1>

<%= render 'form', neighborhood: @neighborhood %>

<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @neighborhood.name %>
</p>

<p>
  <strong>Block count:</strong>
  <%= @neighborhood.block_count %>
</p>

<p>
  <strong>Population:</strong>
  <%= @neighborhood.population %>
</p>

<p>
  <strong>Municipality:</strong>
  <%= @neighborhood.municipality.name %>
</p>

<%= link_to 'Edit', edit_neighborhood_path(@neighborhood) %> |
<%= link_to 'Back', neighborhoods_path %>